### ISSUE TITLE
0.3.3 vs 0.4.4

### ISSUE THREAD

**Issue by daniel-mina97** [rticommunity/rticonnextdds-connector-py#1]
import time
import rticonnextdds_connector as rti

connector = rti.Connector("MyParticipantLibrary::Zero", "xml_files/main.xml")
input = connector.getInput("MySubscriber::CirculateCurrentReader")
while True:
    input.take()
    print input.samples.getLength()
    time.sleep(2)

I am using Python 2.7.15. The above code works perfectly fine in version 0.3.3 of connector, as I am actually able to receive samples as shown by the print statement. If I run this same code with the 0.4.4 version of connector however, the program is unable to receive any samples at all... The xml file is not changed at all. Is there a change you can think of from 0.3.3 to 0.4.4 that would cause something like this? Thanks. 

I've done more fiddling and have come across more weird behavior. If I install version 0.3.3, run the snippet above (I will see that samples are being received), close it, and then install version 0.4.4 and run the snippet above, I will be able to receive samples for a minute or so, but then eventually it will stop receiving samples.... The application that publishes the samples never stops publishing.

**Comment by gianpiero** [comment]
Hello @daniel-mina97 ,

There should not be difference between the two versions when it comes to receive samples. Be aware that now when you iterate through sample you have to start from 0 so old code may miss the first sample and go one over and crash. 

The reason why it stops writing (and the reader receiving) is because the examples are using just a simple xml where the participant has both a data writer and a data reader. So the simple/writer also has a datareader that is not used: because of that, the datawriter will fill up is queue because it is waiting for the datareader to read but it never happens. Try to have two different configuration for the simple/reader and simple/writer. I will keep this ticket closed since you did close it.

**Comment by daniel-mina97** [comment]
Thanks for the response! The reason I closed this was because I realized I should have raised this issue on the rti forums. I actually found a thread made by another individual who seems to also be having issues with 0.4.4. I wrote another comment on that thread. 

[https://community.rti.com/forum-topic/rticonnextdds-connector-python3-problems](url)
