### ISSUE TITLE
Using bitbound enumerators

### ISSUE THREAD

**Issue by TheGrandJonsson** [rticommunity/rticonnextdds-connector-py#135]
Hi!
Is there a way to tag enumerators in the XML-file as bitbound? 
I cant find any references or examples about it in the documentation website. 

If anyone could help that would be great! 
Thanks!

**Comment by TheGrandJonsson** [comment]
Ah, alright. 
Do you have any documentation of what's supported by the XML? 
Alot of the QoS settings aren't specified in the documentation website, it would really help. 
Thanks for the help!

**Comment by samuelraeburn** [comment]
We have [this table](https://community.rti.com/static/documentation/connector/1.1.1/api/python/features.html) that shows the features supported by Connector.
Almost all QoS are fully supported, the exceptions are mutable QoS (such as Ownership Strenght) since they cannot be changed from within Connector) and QoS that have an accompanying API (such as Batch, since there is no flush API).
