### ISSUE TITLE
resource_limits.max_objects_per_thread value

### ISSUE THREAD

**Issue by Andreas71** [rticommunity/rticonnextdds-connector-py#2]
Hello,

I am trying to run the example using threading to run in parallel several readers/writers, but when I try to increase the number of readers/writers to more than 8 I get the following error.

[CREATE Participant] REDAWorkerFactory_createObjectPerWorker:!create objectPerWorker: worker factory's max. storage count reached (you may need to increase resource_limits.max_objects_per_thread value)

I saw a different thread stating how to solve this, but it was for a different language. How can I solve this in python?

Thanks in advance

**Comment by gianpiero** [comment]
Hello @Andreas71,

Thanks for contacting us about the connector. Unfortunately the bug you describe cannot be fixed at the connector level. It's an issue in the Connext library (CORE-8126). 

I think the work around you are referring to is this one for node:[]( https://community.rti.com/forum-topic/solved-how-change-maxobjectsperthread-rticonnextddsconnector)

I similar approach could be used for python but we do not have an implementation of that. 

I'll close this issue here and I'll suggest you contact the official support regarding bug CORE-8126 and mentioning this issue. 

Best Regards,
  Gianpiero
